evolo/urls.py
from django.contrib import admin
from django.urls import path
from evolo import views
from django.contrib.auth import views as auth_views

app_name = 'evolo'
urlpatterns = [
    path('newuser', views.NewUserRegistrationView.as_view(), name='new_registration'),  # new user registration
    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login_view'),
    # VariableMaster
    path('home', views.Home.as_view(), name='home_view'),  # home view
    path('varmaster', views.CreateVariables.as_view(), name='var_create_view'),
    path('varupdate/<int:pk>', views.VariablesUpdate.as_view(), name='var_update'),
    # VariableResults
    path('resultsadd', views.add_results, name='add_results_view'),
    path('resultslist', views.VariableResultsList.as_view(), name='list_results_view'),
    path('delete/<str:dt>', views.delete_variable_results, name="delete_view"),
    path('modify/<str:dt>',views.modify_results,name="modify_view"),

]

evolo_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('evolo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

evolo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.

class VariableMaster(models.Model):
    """Master table to creating tracking varibales - specific to the user"""
    NUMERIC = 'NM'
    CATEGORICAL = 'CT'
    BINARY = 'BN'
    SCALE = 'SC'

    VARIABLE_TYPE_CHOICES = [
        (NUMERIC, 'Numeric'),
        (CATEGORICAL, 'Categorical'),
        (BINARY, 'Binary'),
        (SCALE, 'Scale'),

    ]

    person = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    variable_name = models.CharField(max_length=100)
    variable_type = models.CharField(max_length=2, choices=VARIABLE_TYPE_CHOICES, default=NUMERIC)

    def __str__(self):
        return self.variable_name


class VariableResults(models.Model):
    """store the results of the variables """
    variable = models.ForeignKey(VariableMaster, on_delete=models.CASCADE)
    result_date = models.DateField(null=True,blank=True)
    result_numeric = models.FloatField(null=True, blank=True)
    result_binary = models.BooleanField(default=False, blank=True)
    result_categorical = models.CharField(max_length=200, null=True, blank=True)
    result_scale = models.PositiveSmallIntegerField(null=True, blank=True,
        validators=[MinValueValidator(limit_value=1), MaxValueValidator(limit_value=10)])

    @property
    def result_value(self):
        if self.variable.variable_type == VariableMaster.NUMERIC:
            return self.result_numeric
        elif self.variable.variable_type == VariableMaster.BINARY:
            return self.result_binary
        elif self.variable.variable_type == VariableMaster.CATEGORICAL:
            return self.result_categorical
        else:
            return self.result_scale

    class Meta:
        ordering = ['-result_date']

    def __str__(self):
        return self.variable.variable_name

evolo/forms.py
from django.forms import ModelForm
from django import forms
from .models import VariableMaster,VariableResults
from django.contrib.auth.forms import UserCreationForm
import datetime


class VariableMasterForm(ModelForm):
    """create new varible for tracking"""
    class Meta:
        model = VariableMaster
        fields = ['variable_name','variable_type','person']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['person'].widget = forms.HiddenInput()


class VariableResultsForm(ModelForm):
    class Meta:
        model = VariableResults
        fields = ['result_numeric','result_binary','result_categorical','result_scale']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields['result_categorical'].widget.attrs['class'] = 'form-control'
        self.fields['result_numeric'].widget.attrs['class'] = 'form-control'
        self.fields['result_scale'].widget.attrs['class'] = 'form-control'
        self.fields['result_scale'].widget.attrs['placeholder'] = '1 - 10'

        if self.instance.variable.variable_type == VariableMaster.NUMERIC:

            self.fields['result_binary'].widget = forms.HiddenInput()
            self.fields['result_categorical'].widget = forms.HiddenInput()
            self.fields['result_scale'].widget = forms.HiddenInput()
        elif self.instance.variable.variable_type == VariableMaster.BINARY:

            self.fields['result_numeric'].widget = forms.HiddenInput()
            self.fields['result_categorical'].widget = forms.HiddenInput()
            self.fields['result_scale'].widget = forms.HiddenInput()
        elif self.instance.variable.variable_type == VariableMaster.CATEGORICAL:

            self.fields['result_numeric'].widget = forms.HiddenInput()
            self.fields['result_binary'].widget = forms.HiddenInput()
            self.fields['result_scale'].widget = forms.HiddenInput()
        elif self.instance.variable.variable_type == VariableMaster.SCALE:

            self.fields['result_numeric'].widget = forms.HiddenInput()
            self.fields['result_binary'].widget = forms.HiddenInput()
            self.fields['result_categorical'].widget = forms.HiddenInput()




class NewUserForm(UserCreationForm):
    """New user registration form"""
    def __init__(self,*args,**kwargs):
        super(NewUserForm, self).__init__(*args,**kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

evolo/views.py
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, FormView, DeleteView
from django.views.generic.list import ListView
from .models import VariableMaster, VariableResults
from .forms import VariableMasterForm, VariableResultsForm, NewUserForm
from django.urls import reverse_lazy
import datetime
from django.forms import modelformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class Home(LoginRequiredMixin, ListView):
    """display list of varibales being trcked by a particular user on the Home Page"""
    model = VariableMaster
    template_name = 'evolo/home.html'

    def get_queryset(self):
        qs = VariableMaster.objects.filter(person=self.request.user)
        return qs


class CreateVariables(LoginRequiredMixin, CreateView):
    """add variable for tracking"""
    form_class = VariableMasterForm
    template_name = "evolo/variablemaster_form.html"
    success_url = reverse_lazy('evolo:home_view')

    def get_initial(self):
        data = {'person': self.request.user}
        return data


class VariablesUpdate(LoginRequiredMixin, UpdateView):
    model = VariableMaster
    form_class = VariableMasterForm
    template_name = "evolo/variablemaster_form.html"
    success_url = reverse_lazy('evolo:home_view')


@login_required
def add_results(request):
    """function to add results for a specific date"""

    if request.method == 'GET':

        # record_status = VariableResults.objects.filter(variable__person=request.user,
        #                                                result_date=None).exists()
        # if not record_status:  # create records in results table with None values
        #     variable_obj_list = VariableMaster.objects.filter(person=request.user)
        #     rec_list = [VariableResults(variable=track_var) for track_var in variable_obj_list]
        #     VariableResults.objects.bulk_create(rec_list)

        record_count = VariableResults.objects.filter(variable__person=request.user,
                                                       result_date=None).count()
        variable_obj_list = VariableMaster.objects.filter(person=request.user)
        if record_count !=0:
            if variable_obj_list.count() != record_count:  # a new variable has been created by the user
                VariableResults.objects.filter(variable__person=request.user,
                                               result_date=None).delete()
                record_count = 0

        if record_count == 0:  # create records in results table with None values
            rec_list = [VariableResults(variable=track_var) for track_var in variable_obj_list]
            VariableResults.objects.bulk_create(rec_list)


    VariableFormset = modelformset_factory(VariableResults, form=VariableResultsForm, extra=0)

    if request.method == 'POST':
        formset = VariableFormset(request.POST)
        user_input_dt = request.POST['results_date']  # get the user selected date
        py_user_input_dt = datetime.datetime.strptime(user_input_dt, "%Y-%m-%d")
        previous_rec = VariableResults.objects.filter(variable__person=request.user,
                                                      result_date=py_user_input_dt.date()).exists()
        if previous_rec:  # user has already entered results for this date
            messages.warning(request, f'NOT saved - Results already added for {py_user_input_dt.strftime("%d %b %y")}')
        else:  # save the results
            if formset.is_valid():
                formset.save()
                # update date in the databse , as default date in the object is None
                VariableResults.objects.filter(variable__person=request.user, result_date=None
                                               ).update(result_date=py_user_input_dt.date())

                messages.success(request, 'Results added.')
                return HttpResponseRedirect(reverse_lazy('evolo:list_results_view'))
    else:
        formset = VariableFormset(
            queryset=VariableResults.objects.filter(variable__person=request.user, result_date=None))

    return render(request, 'evolo/add_results.html', {'formset': formset})


def modify_results(request, dt):
    """modify existing results"""
    VariableFormset = modelformset_factory(VariableResults, form=VariableResultsForm, extra=0)
    formset = VariableFormset(request.POST or None,
                              queryset=VariableResults.objects.filter(variable__person=request.user, result_date=dt))
    if request.method == 'POST':
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Results Updated.')
            return HttpResponseRedirect(reverse_lazy('evolo:list_results_view'))

    return render(request, 'evolo/modify_results.html', {'formset': formset})


class VariableResultsList(LoginRequiredMixin, ListView):
    """display variable results entered by the user"""
    model = VariableResults

    def get_queryset(self):
        qs = VariableResults.objects.filter(variable__person=self.request.user,result_date__isnull=False)
        return qs


def delete_variable_results(request, dt):
    """delete exeisting results from the databse"""
    tmp_dt = None
    if dt != 'None':
        try:  # if date is changed in url
            tmp_dt = datetime.datetime.strptime(dt, "%Y-%m-%d").date()
        except:
            messages.warning(request, "Date is invalid")
            return HttpResponseRedirect(reverse_lazy('evolo:list_results_view'))
        else:
            delete_qs = VariableResults.objects.filter(variable__person=request.user, result_date=dt)
    else:
        delete_qs = VariableResults.objects.filter(variable__person=request.user, result_date__isnull=True)

    if request.method == 'POST':
        if request.POST.get('btn_confirm') == 'confirm':
            delete_qs.delete()
            messages.success(request, "Results Deleted")
        else:
            pass
        return HttpResponseRedirect(reverse_lazy('evolo:list_results_view'))

    return render(request, 'evolo/confirm_delete.html', {'del_date': tmp_dt})


# -----------New User Registration------------------------------------------------------------------------------
class NewUserRegistrationView(FormView):
    form_class = NewUserForm
    # form_class = UserCreationForm
    template_name = "evolo/user_registration.html"
    success_url = reverse_lazy('evolo:login_view')

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        messages.success(self.request, f"User-  {username} Created")
        return HttpResponseRedirect(reverse_lazy('evolo:login_view'))

evolo/templates/evolo/add_results.html
{% extends "evolo/base.html" %}
{% block title %}{{ block.super }}- Add Results{% endblock %}
{% block content %}
    <h3 class="text-center text-success">Add Daily Results</h3>
    {% if formset.errors %}
        {% for error in formset.errors %}
            <div class="bg-danger text-white">{{ error }}</div>
        {% endfor %}


    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="row mb-2">
            <div class="col-2">
                <h4>Select Date</h4>
            </div>
            <div class="col-2">
                <input type="date" id="tracker_date" name="results_date"
                required="required" value="{% now "Y-m-d" %}"
                       class="form-control">
            </div>

        </div>
        {{ formset.management_form }}
        <div class="card mb-2 shadow border border-dark" style="border-radius: 10px">
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Variable</th>
                        <th scope="col">Type</th>
                        <th scope="col">Observation</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in formset %}
                        {{ form.id }}

                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ form.instance.variable.variable_name }}</td>
                            <td>{{ form.instance.variable.get_variable_type_display }}</td>
                            <td>{{ form.result_numeric }}{{ form.result_binary }}{{ form.result_categorical }}
                                {{ form.result_scale }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>


            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        {#    <input type="submit" value="Save">#}
    </form>
{% endblock %}

evolo/templates/evolo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
{#    <title>Health Tracker</title>#}
    <title>{% block title %}Health Tracker{% endblock %}</title>
</head>
<body>


<div class="container mt-2">
    {% if request.user.is_authenticated %}


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
  <div class="container-fluid">
{#    <a class="navbar-brand" href="#">Navbar</a>#}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'evolo:home_view' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'evolo:add_results_view' %}">Daily Results</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'evolo:var_create_view' %}">Create New Variables</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'evolo:list_results_view' %}">View Results</a>
        </li>

      </ul>
        <span class="navbar-text">
            {{ request.user|capfirst }}
      </span>
        <span class="navbar-text">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </span>
    </div>
  </div>
</nav>

<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}

    {% endif %}
</div>
{% endif %}
    {% block content %}{% endblock %}
</div>
</body>
</html>

evolo/templates/evolo/confirm_delete.html
{% extends "evolo/base.html" %}
{% block title %}{{ block.super }}- Delete Results{% endblock %}
{% block content %}
    <form action="{% url 'evolo:delete_view' del_date %}" method="post">
        {% csrf_token %}
        <h3>Are you sure you want to delete the Results for <span class="text-primary">{{ del_date }}</span></h3>

            <button type="submit" class="btn btn-danger" name="btn_confirm" value="confirm">Confirm</button>
            <button type="submit" class="btn btn-success" name="btn_cancel" value="cancel">Cancel</button>


    </form>
{% endblock %}

evolo/templates/evolo/home.html
{% extends "evolo/base.html" %}
{% block title %}{{ block.super }}- Dashboard{% endblock %}
{% block content %}
    <h3 style="text-align: center" class="">Welcome to Home Page <span
            style="color: blue">{{ request.user|capfirst }}</span></h3>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Tracking Variable</th>
            <th scope="col">Variable Type</th>
            <th scope="col">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ object.variable_name }}</td>
                <td>{{ object.get_variable_type_display }}</td>
                <td><a class="nav-link" href="{% url 'evolo:var_update' object.id %}">Edit</a></td>
            </tr>
        {% empty %}
            <h3 class="text-danger">Tracking variables not created</h3>
        {% endfor %}
        </tbody>
    </table>



{% endblock %}

evolo/templates/evolo/modify_results.html
{% extends "evolo/base.html" %}
{% block title %}{{ block.super }}- Modify Results{% endblock %}
{% block content %}
    <h3 class="text-center text-success">Modify Results</h3>
    {% if formset.errors %}
        {% for error in formset.errors %}
            <div class="bg-danger text-white">{{ error }}</div>
        {% endfor %}


    {% endif %}
    <form method="post">
        {% csrf_token %}

        {{ formset.management_form }}
        <div class="card mb-2 shadow border border-dark" style="border-radius: 10px">
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Variable</th>
                        <th scope="col">Type</th>
                        <th scope="col">Observation</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in formset %}
                        {{ form.id }}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ form.instance.variable.variable_name }}</td>
                            <td>{{ form.instance.variable.get_variable_type_display }}</td>
                            <td>{{ form.result_numeric }}{{ form.result_binary }}{{ form.result_categorical }}
                                {{ form.result_scale }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>


            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        {#    <input type="submit" value="Save">#}
    </form>
{% endblock %}

evolo/templates/evolo/user_registration.html
{% extends "evolo/base.html" %}
{% block title %}{{ block.super }}- User Registration{% endblock %}
{% block content %}
    <h3 class="text-center text-success mt-5">New User Registration</h3>
    {{ form.errors }}
    <div class="row col-sm-5">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create User</button>
    </form>
    </div>
{% endblock %}

evolo/templates/evolo/variablemaster_form.html
{% extends "evolo/base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}

    {{ form.as_p }}


    <button type="submit" class="btn btn-primary">Submit</button>

</form>
{% endblock %}

evolo/templates/evolo/variableresults_list.html
{% extends "evolo/base.html" %}
{% block title %}{{ block.super }}- Results List{% endblock %}
{% block content %}


    <div class="row mb-5">
        <div class="col"><span class="badge bg-primary">Variable Name</span></div>
        <div class="col"><span class="badge bg-primary">Type</span></div>
        <div class="col"><span class="badge bg-primary">Value</span></div>
    </div>
    {% for variableresults_rec in variableresults_list %}
        {% ifchanged variableresults_rec.result_date %}
            <div class="row mt-2">
                <div class="col-10">
                    <span class="badge rounded-pill bg-success mb-2">{{ variableresults_rec.result_date }}</span>
                </div>
                <div class="col">
                    <a class="btn btn-success btn-sm"
                       href="{% url 'evolo:modify_view' variableresults_rec.result_date %}"
                       role="button">Modify</a>
                </div>
                <div class="col">
                    <a class="btn btn-danger btn-sm"
                       href="{% url 'evolo:delete_view' variableresults_rec.result_date %}"
                       role="button">Delete</a>
                </div>
            </div>
        {% endifchanged %}
        <div class="row border-bottom border-dark">
            <div class="col">{{ variableresults_rec.variable }}</div>
            <div class="col">{{ variableresults_rec.variable.get_variable_type_display }}</div>
            <div class="col">
                {% if variableresults_rec.variable.variable_type  == "BN" %}
                    {{ variableresults_rec.result_value|yesno:"Yes,No,maybe" }}
                {% else %}
                    <div class="col">{{ variableresults_rec.result_value }}</div>
                {% endif %}
            </div>

        </div>
    {% empty %}
        <h3>No results </h3>
    {% endfor %}



{% endblock %}